links:
  rails:
    root: "https://www.railstutorial.org"
    book: "https://www.railstutorial.org/book"
    help: "https://www.railstutorial.org/help"
    new: "http://news.railstutorial.org"
    contact: "https://www.railstutorial.org/contact"
  screencast: "http://screencasts.railstutorial.org"
  ruby_on_rails: "http://rubyonrails.org"
  michaelhartl: "http://www.michaelhartl.com"
layouts:
  application:
    logo: "#"
    nav:
      home: "#"
      help: "#"
      login: "#"
  footer:
    nav:
      about: "#"
      contact: "#"
models:
  user:
    email:
      regexp_valid: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    name:
      max_length: 50
    email:
      max_length: 255
    password:
      min_length: 6
      max_length: 40
